### INDEX Cars
GET http://localhost:3000/cars

### CREATE Cars
POST http://localhost:3000/cars
content-type: application/json

{
  "input_make": "Honda",
  "input_model": "Accord",
  "input_year": 1997,
  "input_name": "Bronze and Bougie",
  "input_image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4ELWSU8NxFQ_4iaoTmtMGPIkXkrIrcZu20Q&usqp=CAU"
}


### SHOW Cars
GET http://localhost:3000/cars/2

### UPDATE Cars
PATCH http://localhost:3000/cars/1
content-type: application/json

{
  "input_image_url": "image url here"
}

### DESTROY Cars
DELETE http://localhost:3000/cars/7

